language: cpp

compiler:
  - clang++-3.6
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make tau
  - make m-tau

before_install:
  - sudo add-apt-repository ppa:h-rayflood/llvm
  - sudo apt-get update -qq
  - sudo apt-get install -qq  libboost-regex-dev libboost-dev  clang-3.6

install: ./build-libmarpa.sh
